version: '3.8'

services:
  frontend:
    image: signalacr.azurecr.io/whatshot/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - whatshot-network

  backend:
    image: signalacr.azurecr.io/whatshot/backend:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - whatshot-network

networks:
  whatshot-network:
    driver: bridge 