FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy all files
COPY . .

# Expose the backend port
EXPOSE 4000

# Start the backend server
CMD ["node", "server.cjs"] 